# Generated by Django 5.0.4 on 2024-04-09 14:29

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyManufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название компании')),
            ],
            options={
                'verbose_name': 'компания производитель',
                'verbose_name_plural': 'компании производители',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShelfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, unique=True, verbose_name='период хранения препарата')),
            ],
            options={
                'verbose_name': 'срок хранения',
                'verbose_name_plural': 'сроки хранения',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название препарата')),
                ('image', models.ImageField(blank=True, default='product_images/scale_1200.png', null=True, upload_to=main.models.product_image_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='фото препарата')),
                ('composition', models.TextField(help_text='через запятую перечислите состав продукта', verbose_name='состав продукта')),
                ('quantity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0, message='количество не может быть отрицательным')], verbose_name='количество упаковок')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='цена(KZT)')),
                ('company_manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.companymanufacturing', verbose_name='компания производитель')),
                ('shelf_life', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.shelflife', verbose_name='срок хранения препарата')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('-title',),
            },
        ),
    ]
