# Generated by Django 5.0.3 on 2024-03-28 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyManufacturingChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название компании')),
            ],
            options={
                'verbose_name': 'компания производитель',
                'verbose_name_plural': 'компании производители',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShelfLifeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, unique=True, verbose_name='период хранения препарата')),
            ],
            options={
                'verbose_name': 'срок хранения',
                'verbose_name_plural': 'сроки хранения',
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='название препарата')),
                ('image', models.ImageField(blank=True, default='scale_1200.png', null=True, upload_to='product_images/<django.db.models.fields.CharField>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='фото препарата')),
                ('composition', models.TextField(help_text='через запятую перечислите состав продукта', verbose_name='состав продукта')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(0, message='количество не может быть отрицательным')], verbose_name='количество упаковок')),
                ('company_manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.companymanufacturingchoices', verbose_name='компания производитель')),
                ('shelf_life', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.shelflifechoices', verbose_name='срок хранения препарата')),
            ],
        ),
    ]
