# Generated by Django 5.0.3 on 2024-03-28 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_companymanufacturingchoices_companymanufacturing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0, message='количество не может быть отрицательным')], verbose_name='количество упаковок'),
        ),
    ]
